// priority: 100

ServerEvents.recipes(event => {
    event.remove({ output: 'ae2:controller' })
    event.remove({ output: 'ae2:drive' })
    event.remove({ output: 'ae2:cell_component_1k' })
    event.remove({ output: 'ae2:calculation_processor_press' })
    event.remove({ output: 'ae2:engineering_processor_press' })
    event.remove({ output: 'ae2:logic_processor_press' })
    event.remove({ output: 'ae2:silicon_press' })
    event.remove({ output: 'ae2:name_press' })
    event.remove({ id: 'ae2:network/cables/glass_fluix' })
    event.remove({ output: 'ae2:construction_core' })
    event.remove({ output: 'ae2:destruction_core' })
    event.remove({ output: 'ae2:blank_pattern' })
    event.remove({ output: 'ae2:terminal' })
    event.remove({ output: 'ae2:crafting_terminal' })
    event.remove({ output: 'ae2:pattern_encoding_terminal' })
    event.remove({ output: 'ae2:pattern_access_terminal' })
    event.remove({ output: 'ae2:interface' })
    event.remove({ output: 'ae2:pattern_provider' })
    event.remove({ output: 'ae2:molecular_assembler' })
    event.remove({ output: 'ae2:crafting_unit' })
})