#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 09 19:15:35 SGT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=
enableShaders=false
