#Truly Dark properties file
#Sat Jul 04 22:21:39 SGT 2026
dark_nether_fog=0.5
only_affect_block_light=false
moon_phase_intensity=0.0
sky_merge=true
dark_overworld=true
dark_default=false
biome_blacklist=alexscaves\:primordial_caves,alexscaves\:candy_cavity
cloud_darkness=0.1
hard_lock=false
dark_nether=false
require_client_mod=false
setup_version=Manual
dark_end_fog=0.0
dark_moon=true
dark_sky=true
pack_configured=false
dark_end=false
dark_skyless=false
sky_darkness=0.0
fog_darkness=0.0
ignore_moon_phase=true
entity_light_floor=0.03
